base_db: &base_db
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *base_db
  database: <%= ENV[ 'PROPILE_DEV_DB_NAME' ] %>
  username: <%= ENV[ 'PROPILE_DEV_DB_USER' ] %>
  password: <%= ENV[ 'PROPILE_DEV_DB_PASS' ] %>

test:
  <<: *base_db
  database: <%= ENV[ 'PROPILE_TEST_DB_NAME' ] %>
  username: <%= ENV[ 'PROPILE_TEST_DB_USER' ] %>
  password: <%= ENV[ 'PROPILE_TEST_DB_PASS' ] %>

production:
  <<: *base_db
  database: <%= ENV[ 'PROPILE_PROD_DB_NAME' ] %>
  username: <%= ENV[ 'PROPILE_PROD_DB_USER' ] %>
  password: <%= ENV[ 'PROPILE_PROD_DB_PASS' ] %>
  host: <%= ENV[ 'PROPILE_PROD_DB_HOST' ] %>
  
